
spring:
  application:
    name: retelling-bot
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: retelling_bot
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  liquibase:
    enabled: true
    change-log: ./db/changelog/changelog-master.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.0
          max-tokens: 8192

retelling:
  executors:
    tg-listener:
      threads: 10
      queue-capacity: 1000
  scheduled-jobs:
    source-parsing:
      habr-cron: 0 0 * * * *
    retelling:
      cron: 0 * * * * *
  data-finder:
    habr:
      period-of-days-to-look-for: 1

  prompt:
    retelling: ${PROMPT_RETELLING}
    rate-material: ${PROMPT_RATE_MATERIAL}

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

logging:
  level:
    root: INFO
  console:
    enabled: true