
server:
  port: 8082
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: video-retelling-bot
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: video_retelling_bot
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  liquibase:
    enabled: true
    change-log: ./db/changelog/changelog-master.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.0
          max-tokens: 8000 # Токенов специально немного меньше максимума

retelling:
  admin:
    user-ids: [ 368837634 ]
  yt-subtitles-loader-jar-path: "/Users/nikolay/dev/shell-services/yt-subtitles-loader-1.0.0-RC2.jar"
  rest-timeout: 180000
  dialog-context-limit-tokens: 200000
  feedback:
    form-url: ${FEEDBACK_FORM_URL:}
    show-every-n-retellings: 5

telegram:
  bot:
    name: ${BOT_NAME}
    token: ${BOT_TOKEN}

logging:
  config: classpath:ru/panyukovnn/referenceloggingstarter/logback-spring.xml
  level:
    root: INFO
  console:
    enabled: true
  web-logging:
    log-body: true