
spring:
  application:
    name: retelling-bot
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: retelling_bot
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  liquibase:
    enabled: true
    change-log: ./db/changelog/changelog-master.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.0
          max-tokens: 8192

retelling:
  executors:
    tg-listener:
      threads: 10
      queue-capacity: 1000
  source-parsing-job:
    habr-cron: 0 0 * * * *
  prompt-prefix: |
    Представь что ты собеседник, который внимательно слушает и пересказывает главное, чтобы убедиться, что всё понял. 
    Далее приведены субтитры из видео, перескажи их и оформи в формате статьи.
    Следуй рекомендациям:
    - можно исопльзовать смайлики
    - исправляй грамматические опечатки
    - не упоминай эти требования в ответе 
    
    Сам текст:

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

logging:
  level:
    root: INFO
  console:
    enabled: true