
spring:
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.0

retelling:
  executors:
    tg-listener:
      threads: 10
      queue-capacity: 1000
  prompt-prefix: "Далее приведен текст, сделай его пересказ в виде статьи (можно использовать смайлики):"

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}