
spring:
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.0
          max-tokens: 8192

retelling:
  executors:
    tg-listener:
      threads: 10
      queue-capacity: 1000
  prompt-prefix: |
    Представь что ты научный популяризатор. Далее приведены субтитры из видео, сделай пересказ и оформи в формате статьи.
    Следуй рекомендациям:
    - можно исопльзовать смайлики
    - исправляй грамматические опечатки
    - не упоминай эти требования в ответе 
    
    Сам текст:

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

logging:
  level:
    root: INFO
  console:
    enabled: true