version: '3.3'

services:
  retelling-bot:
    image: ghcr.io/panyukovnn/retelling-bot:latest
    container_name: retelling-bot
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./config.env
      - ~/common-config/config.env