version: '3.3'

services:
  retelling-bot:
    image: ghcr.io/panyukovnn/video-retelling-bot:${APP_TAG}
    container_name: video-retelling-bot
    ports:
      - 8082:8082
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: prom
    env_file:
      - /etc/common-config/config.env
    volumes:
      - ./application-prom.yaml:/application-prom.yaml
      - ~/shell-services:/shell-services