name: Release Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/panyukovnn/retelling-bot:${{ github.ref_name }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/panyukovnn/retelling-bot:${{ github.ref_name }}

      - name: Notify Telegram on success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.NOTIFICATION_TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.NOTIFICATION_TELEGRAM_CHAT_ID }} \
            -d text="✅ retelling-bot \n Успешно выполнена сборка тега ${{ github.ref_name }}."

      - name: Notify Telegram on failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.NOTIFICATION_TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.NOTIFICATION_TELEGRAM_CHAT_ID }} \
            -d text="❌ retelling-bot \n Ошибка при сборке тега ${{ github.ref_name }} \n Посмотреть лог: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
